version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Europe/London'
    reviewers:
      - 'koenoe'
    labels:
      - 'npm'
      - 'dependencies'
    update-types:
      - 'minor'
      - 'patch'
    ignore:
      - dependency-name: 'next'
        versions: ['*']
        update-types: ['minor', 'patch']
    allow:
      - dependency-name: 'next'
        versions: ['>= 0.0.0-canary']
